### PR TITLE
Fix custom error presentation messing with user code

### LINKED ISSUE #4: Custom error presentation logic messes with the behaviour of my code
I'm opening this issue to discuss a matter that doesn't have a straight-forward enough solution for a PR.

My code uses the `.stack` property in Error instances. Overriding `Error.prepareStackTrace` before running a test, as done in the snippet below, means that while I'm testing this functionality, my code behaves differently from how it should.

https://github.com/bearror/oletus/blob/ad56f38dbe810e067ad4860f35e12927c5b24cbe/oletus.mjs#L4

I have attempted to fix this issue without success, by moving the location where `prepareStackTrace` is overridden closer to where `.stack` is accessed by Oletus:

https://github.com/Avaq/oletus/blob/309e79c0e19b2a949aedc4d26aeb89fc8f19744d/oletus.mjs#L18-L21

Yet I realize that even if I were successful, there is another issue with Oletus' approach to formatting errors, and that is that it assumes that all assertions are made directly at the testing location, and thus that only the first stack trace entry is relevant to the user.

For me, this is not the case. I have abstracted over assertions, and therefore Oletus shows me the same location for every failing assertion. It might therefore be worth considering the removal of the custom error formatting logic altogether, and just presenting the user with the default `e.stack` as a message.

If you do just present `e.stack`, then a user can always modify the output from that by overriding `Error.prepareStackTrace` themselves.

### PR DESCRIPTION
**Pull request by Avaq**
# Motivation

To fix #4

# Changes

latest-screenshot

- File names in the location now include directories relative to the current working directory
- The location now contains up to five stack frames, as opposed to one
- Sadly, when the error was thrown asynchronously, formatting of location uses a fallback approach that has slightly different semantics (see changes in unit tests)
- But most importantly, formatting of the stack trace happens without affecting user code

### CODE REVIEW

**Comment by Avaq** [comment]
> Sadly, when the error was thrown asynchronously, formatting of location uses a fallback approach

The reason for this, it seems, is that V8 wants `Error.prepareStackTrace` to be set *while the Error instance is created* in order for it to take effect. The problem with asynchronously created errors then becomes that we cannot override this function during multiple ticks, because as we've seen, that affects user code. And we cannot capture the stack again, as we're doing with synchronous errors, because by the time the error makes it to our handler, we're already in a new frame.

**Comment by Avaq** [comment]
There probably is some way to intercept the creation of the Error even if it's asynchronous, using the `async_hook` module, as suggested here: https://stackoverflow.com/a/54954438/1001417

But I think the current implementation suffices for now and I want to let it rest for a bit. :)

**Comment by bearror** [comment]
Looks like a sensible approach to me.

The only problem I was able to find for now is that there are some Node version oddities involved. In **v10.16.3** and **v11.4.0** `extractTraceFallback` receives `'/test/test.mjs:94'`, which is then promptly filtered. Whereas **v12.10.0** gets the entire trace the filtering was designed for.

**Comment by bearror** [comment]
Merging this even though it'll break the build for the time being. I have some fixes to apply before bumping the version -- those being
- the above mentioned `extractTraceFallback` filtering should work correctly for Node versions 9, 10, and 11 as well as 12,
- making the tests more lenient on the location output such that it is actually possible for different Node versions to pass, and
- making the example module properly pass the fixtures.

Going to take a look at the repository as a whole as well. Now might be the time to take another pass at the tests, add actual version tags, some JSDoc annotations, and possible refactorings. 😄

---

You can expect the version that doesn't mess with `Error.prepareStackTrace` on NPM later this week. I'll be making all future changes via. PRs for better visibility.

**Comment by Avaq** [comment]
> Going to take a look at the repository as a whole as well

Awesome! :)

> You can expect the version that doesn't mess with `Error.prepareStackTrace` on NPM later this week.

Thanks!

> I'll be making all future changes via. PRs for better visibility.

Just ping me if you'd like a second pair of eyes

**Comment by bearror** [comment]
Will do! 👍

**Pull request merged**
