### PR TITLE
Update module structure

### PR DESCRIPTION
**Pull request by Conaclos**
Hi!

This PR enables to support the new node16/nodenext module resolution of the [upcoming TypeScript version](https://devblogs.microsoft.com/typescript/announcing-typescript-4-7-rc/#ecmascript-module-support-in-node-js).

I took the opportunity to switch from `.mjs` extension to `.js` extension. I introduced redirections in exports map of package.json to avoid breaking changes.

### CODE REVIEW

**Comment by Conaclos** [comment]
@bearror
Any thoughts?

**Comment by bearror** [comment]
Heya. Sorry for the long radio silence!

As I'm getting back into gear with OSS, I'll have to figure out what to do with this project. To be frank, I'd really like to just have a hassle-free test runner without additional dependencies. Deno has one out of the box. Node seems to be getting a built-in test runner too. Not sure Oletus is really needed in that case, which is great. Since Oletus is little more than a test runner built around the Node assertion module, there shouldn't bee too much work to swap over.

That said, I don't see any problem getting this change merged and published, although admittedly it's a year late. 😅

**Comment by Conaclos** [comment]
I missed your reply ^^

> I'd really like to just have a hassle-free test runner without additional dependencies

Same there.

> Deno has one out of the box. Node seems to be getting a built-in test runner too

Bun is also shipping its jest-compatible test runner.
However, for now I see several issues with these test runners:

- bun is not mature enough (no test coverage)
- node reporters are not really human-readable
- deno is a bit incompatible with the rest of the ecosystem

These limitations should be overcome in coming months, or in the coming year.

For now, I am still using oletus. I would like to have this PR merged.

By the way, could you add me as a maintainer on github / npm? I could update the codebase if needed.

have  a nice day!

**Comment by bearror** [comment]
Good points. I'm in no hurry to deprecate Oletus either, and I'll have to admit the TAP output from the Node test runner is pretty rough for now.

> By the way, could you add me as a maintainer on github / npm? I could update the codebase.
Sure thing. What's your NPM user?

**Review by bearror — APPROVED** [review]
Finally reviewed and checked this out locally. Since the engine version requirements are now stricter, this probably calls for a `v4.0.0`, even though the actual API is unchanged.

Given that we have similar goals for Oletus and you've already contributed solid changes, I'd be happy to have you on as a contributor. I don't mind cutting the new version and releasing it, or if you'd like to use this as a simple smoke test to see that you can get changes published, that'd work for me too. Let me know your preference.

It's still surprising to see this has actual usage. 😅 Feel free to ping me in the future, and I'll try to give Oletus more attention.

**Comment by Conaclos** [comment]
I am using the [same pseudo on NPM](https://www.npmjs.com/~conaclos).

> I don't mind cutting the new version and releasing it.

i have no time for doing this today. Feel free to release it if you have time :)
Otherwise, I will do it when I find some time :)

> It's still surprising to see this has actual usage.

Ahah. I tested several dependency-free test runners for migrating from AVA. oletus had the simplest migration path.

**Comment by bearror** [comment]
Published as `v4.0.0`. Kinda feels wrong doing a major for this, but from the little looking around I did, it seems to be the right call when the engine version changes. 🤷 

I've sent the maintainer invitations to you @Conaclos. Thanks for the contributions again, and sorry for the long wait!

**Pull request merged**
